### ISSUE TITLE
NPX?

### ISSUE THREAD

**Issue by mrpupil** [out386/TelegramMirrorBot#127]
When i star with !npm start I get this error 
> mirror-bot@2.0.0 start /content/aria-telegram-mirror-bot
> npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

>npx: installed 1 in 1.705s

**Comment by out386** [comment]
That is not an error. If you're getting an error, it'll appear after that last "npx" line.

**Comment by mrpupil** [comment]
>Found 9 errors.

>npm ERR! code ELIFECYCLE
>npm ERR! errno 2
>npm ERR! mirror-bot@2.0.0 start: `npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js`
>npm ERR! Exit status 2
>npm ERR! 
>npm ERR! Failed at the mirror-bot@2.0.0 start script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by out386** [comment]
The actual error is between your 1st and 2nd messages. Show the entire thing.

**Comment by mrpupil** [comment]
sorry i thought it wasn't important, the message is the same as in the compilation of .constants

> mirror-bot@2.0.0 start /content/aria-telegram-mirror-bot
> npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js

npx: installed 1 in 1.703s
src/bot_utils/event_regex.ts:14:19 - error TS2339: Property 'COMMANDS_USE_BOT_NAME' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 6 more ...; readonly DOWNLOAD_NOTIFY_TARGET: { ...; }; }'.

14     if (constants.COMMANDS_USE_BOT_NAME && constants.COMMANDS_USE_BOT_NAME.ENABLED) {
                     ~~~~~~~~~~~~~~~~~~~~~

src/bot_utils/event_regex.ts:14:54 - error TS2339: Property 'COMMANDS_USE_BOT_NAME' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 6 more ...; readonly DOWNLOAD_NOTIFY_TARGET: { ...; }; }'.

14     if (constants.COMMANDS_USE_BOT_NAME && constants.COMMANDS_USE_BOT_NAME.ENABLED) {
                                                        ~~~~~~~~~~~~~~~~~~~~~

src/bot_utils/event_regex.ts:20:45 - error TS2339: Property 'COMMANDS_USE_BOT_NAME' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 6 more ...; readonly DOWNLOAD_NOTIFY_TARGET: { ...; }; }'.

20           commands[i] = command + constants.COMMANDS_USE_BOT_NAME.NAME + commandAfter[i];
                                               ~~~~~~~~~~~~~~~~~~~~~

src/drive/drive-upload.ts:55:18 - error TS2339: Property 'IS_TEAM_DRIVE' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 6 more ...; readonly DOWNLOAD_NOTIFY_TARGET: { ...; }; }'.

55   if (!constants.IS_TEAM_DRIVE || (constants.IS_TEAM_DRIVE && !isFolder)) {
                    ~~~~~~~~~~~~~

src/drive/drive-upload.ts:55:46 - error TS2339: Property 'IS_TEAM_DRIVE' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 6 more ...; readonly DOWNLOAD_NOTIFY_TARGET: { ...; }; }'.

55   if (!constants.IS_TEAM_DRIVE || (constants.IS_TEAM_DRIVE && !isFolder)) {
                                                ~~~~~~~~~~~~~

src/drive/drive-upload.ts:76:17 - error TS2339: Property 'DRIVE_FILE_PRIVATE' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 6 more ...; readonly DOWNLOAD_NOTIFY_TARGET: { ...; }; }'.

76   if (constants.DRIVE_FILE_PRIVATE && constants.DRIVE_FILE_PRIVATE.ENABLED) {
                   ~~~~~~~~~~~~~~~~~~

src/drive/drive-upload.ts:76:49 - error TS2339: Property 'DRIVE_FILE_PRIVATE' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 6 more ...; readonly DOWNLOAD_NOTIFY_TARGET: { ...; }; }'.

76   if (constants.DRIVE_FILE_PRIVATE && constants.DRIVE_FILE_PRIVATE.ENABLED) {
                                                   ~~~~~~~~~~~~~~~~~~

src/drive/drive-upload.ts:79:33 - error TS2339: Property 'DRIVE_FILE_PRIVATE' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 6 more ...; readonly DOWNLOAD_NOTIFY_TARGET: { ...; }; }'.

79     for (var email of constants.DRIVE_FILE_PRIVATE.EMAILS) {
                                   ~~~~~~~~~~~~~~~~~~

src/index.ts:577:19 - error TS2339: Property 'IS_TEAM_DRIVE' does not exist on type '{ readonly TOKEN: string; readonly ARIA_SECRET: string; readonly ARIA_DOWNLOAD_LOCATION: string; readonly ARIA_DOWNLOAD_LOCATION_ROOT: string; readonly ARIA_FILTERED_DOMAINS: any[]; ... 6 more ...; readonly DOWNLOAD_NOTIFY_TARGET: { ...; }; }'.

577     if (constants.IS_TEAM_DRIVE && isFolder) {
                      ~~~~~~~~~~~~~


Found 9 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mirror-bot@2.0.0 start: `npx typescript && NTBA_FIX_319=1 node --max_old_space_size=128 ./out/index.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the mirror-bot@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by iamLiquidX** [comment]
Did u run tsc command

**Comment by out386** [comment]
@mrpupil, you deleted some fields from constants. Follow step 3 of the Installation section again, then read this: https://github.com/out386/aria-telegram-mirror-bot#constants-description
Do not delete anything you aren't using. Set any such fields to "false" or empty, depending on the type.

@begginer-123, that's not needed anymore.

**Comment by iamLiquidX** [comment]
not needed anymore , wow , so can we run it on low ram config ? like less than 1gb ram config.

**Comment by out386** [comment]
> not needed anymore , wow , so can we run it on low ram config ? like less than 1gb ram config.

Not needed as in `npm start` runs it. If you can't run the typescript compiler, you could just compile it on your local pc, then push ./out to the server.

**Comment by iamLiquidX** [comment]
> > not needed anymore , wow , so can we run it on low ram config ? like less than 1gb ram config.
> 
> Not needed as in `npm start` runs it. If you can't run the typescript compiler, you could just compile it on your local pc, then push ./out to the server.

thank you for the reply, that a really nice addition.

**Comment by mrpupil** [comment]
@out386 Thanks you for your support! Glad it helped @begginer-123 too :smile:
